function new-site-rails -d "Creates a new rails site in /serenity/projects"

 cd /serenity/projects
 mkdir $argv[1]
 cd $argv[1]
 rails new . -B
 skeletons default rails 
 cp /serenity/config/gemfile ./Gemfile

 echo "# $argv[1]" > config/nginx.conf
 echo "# GENERATED by new-site-rails" > config/nginx.conf
 echo "server {" >> config/nginx.conf
 echo " listen 80;" >> config/nginx.conf
 echo -s " server_name " $argv[1] "." (hostname) ";" >> config/nginx.conf
 echo -s " root /serenity/projects/" $argv[1] "/public;" >> config/nginx.conf
 echo " passenger_enabled on;" >> config/nginx.conf
 echo " rack_env development;" >> config/nginx.conf
 echo "}" >> config/nginx.conf

 echo "# $argv[1]" > config/production.conf
 echo "# GENERATED by new-site-rails" > config/production.conf
 echo "server {" >> config/production.conf
 echo " listen 80;" >> config/production.conf
 echo -s " server_name " $argv[1] "." (hostname) ";" >> config/production.conf
 echo -s " root /serenity/projects/" $argv[1] "/public;" >> config/production.conf
 echo " passenger_enabled on;" >> config/production.conf
 echo " rack_env production;" >> config/production.conf
 echo "}" >> config/production.conf

 echo ""
 editor Gemfile
 bundle install
 rake db:create
 rweb

 crow success "Site $argv[1] is now ready"

end
